stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  prepare_model:
    cmd: python src/cnnClassifier/pipeline/stage_03_prepare_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_prepare_model.py
      - config/config.yaml
      - src/cnnClassifier/pipeline/stage_02_dataloader.py
    outs:
      - artifacts/prepare_model

  trainer:
    cmd: python src/cnnClassifier/pipeline/stage_04_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_trainer.py
      - config/config.yaml
      - src/cnnClassifier/pipeline/stage_02_dataloader.py
      - artifacts/prepare_model
    params:
      - BATCH_SIZE
      - EPOCHS
      - LEARNING_RATE
    outs:
      - artifacts/trainer
    metrics:
      - scores.json:
          cache: false
