artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1cgIuTAA10mEoWevfdwvyVJpUerR2DbLD/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

dataloader:
  root_dir: artifacts/dataloader
  train_dir: artifacts/data_ingestion/train
  test_dir: artifacts/data_ingestion/test
  image_transforms_path: artifacts/dataloader/transforms.pth


prepare_model:
  root_dir: artifacts/prepare_model
  base_model_path: artifacts/prepare_model/base_model.pth
  updated_model_path: artifacts/prepare_model/updated_model.pth

trainer:
  root_dir: artifacts/trainer
  trained_model_path: artifacts/trainer/model.pth
  updated_model_path: artifacts/prepare_model/updated_model.pth
  mlflow_uri: https://dagshub.com/RoyalNam/dog-classification.mlflow